language: python
python:
  - '3.8'

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="immolocation.settings.travis"

services:
  - postgresql

script:
  - python3 manage.py test