# Generated by Django 2.2.4 on 2020-06-03 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('email_paypal', models.EmailField(max_length=254)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(default=None, max_length=17)),
                ('date_of_birth', models.DateField(default=None)),
                ('postal_address', models.CharField(default=None, max_length=25)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', user.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MyRental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_city', models.CharField(default=None, max_length=255)),
                ('rental_country', models.CharField(default=None, max_length=25)),
                ('email_user_rental', models.EmailField(default=None, max_length=254, null=True)),
                ('code', models.IntegerField()),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='rental', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'MyRental',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('date_min', models.CharField(default=None, max_length=11)),
                ('date_max', models.CharField(default=None, max_length=11)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Booking',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Announces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=255)),
                ('address', models.CharField(default=None, max_length=25)),
                ('description', models.CharField(default=None, max_length=255)),
                ('country', models.CharField(default=None, max_length=255)),
                ('city', models.CharField(default=None, max_length=255)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('pics_1', models.ImageField(blank=True, null=True, upload_to='../media')),
                ('pics_2', models.ImageField(blank=True, null=True, upload_to='../media')),
                ('pics_3', models.ImageField(blank=True, null=True, upload_to='../media')),
                ('code', models.IntegerField()),
                ('price_weeks', models.IntegerField(default=None)),
                ('price_day', models.IntegerField(default=None)),
                ('date', models.DateField(default=None, null=True)),
                ('booking', models.CharField(default=None, max_length=100, null=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='announce', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Announces',
                'ordering': ['id'],
                'managed': True,
            },
        ),
    ]
