# Generated by Django 2.2.4 on 2020-06-05 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announces',
            name='date',
        ),
    ]
